---
title: "Take-home Exercise 1"
author: "Fong Bao Xian"
date: "6 May 2023"
date-modified: "`r Sys.Date()`"
---

## Data Cleaning

-   Take hint from the data format mentioned in the exercise document. For education level, should change to factor and change the level

-   FinancialJournal - change the diff categories of income/expenses into individual columns - use pivoting / extract year_month from date

    -   Must be able to apply appropriate data wrangling methods to derive analytics\
        table at participant level

    -   Encode all expenses into positive

    -   Must be able to flag out 131 participants which are potentially no longer resident\
        in the city.

    -   Must be able to flag potential anomalous wages on 1st March 2018

-   Take note whether got duplicates / spelling errors?

Plotting

-   When plotting out, good to include more comments in code chunk to explain

-   When we want to show normality, instead of showing statistical results, need to see how to present in charts (qqplot) + statistical results beside

-   When we use ggstatsplot, remember to set.seed else will always get different results

-   In real-life we always assume we do not know the population variance, so will use unequal variance (ggbetweenplot default equal var already set to False so no need to adjust)

-   First do normality test, if not normal then we use non-parametric, and the centrality measure is median

-   Don't have to generate too many plots/analyses. Focus on some areas.
