project:
  type: website

website:
  title: "ISSS608 Visual Analytics and Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 1"
          href: "In-class Ex/In-class_Ex01/In-class_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto
  warning: false

editor: visual

